name: 04 - Using Actions
on:
    push:
    
jobs:
    build:
        runs-on: ubutnu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 
            - name: Printing Folders
              run: ls