name: 06 - Contexts
run-name: 06 Context | DEBUG - ${{inputs.debug}}
on: 
    # push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
env:
    MY_WORKFLOW_ENV: "workflow"
    MY_OVERWRITTEN_ENV: "workflow"
jobs:
    echo-data:
        runs-on: ubuntu-latest
        env: 
          MY_JOB_ENV: "job"
          MY_OVERWRITTEN_ENV: "job"   
        steps:
            - name: Display Information
              run: |
               echo "1. Event name: ${{github.event_name}}"
               echo "2. Ref: ${{github.ref}} "
               echo "3. SHA: ${{github.sha}}"
               echo "4. Actor: ${{github.actor}}"
               echo "5. Workflow: ${{github.workflow}}"
               echo "6. Run ID: ${{github.run_id}}"
               echo "7. Run number: ${{github.run_number}}"
            - name: Rereieve variable
              run: |
                echo "Variable value: ${{vars.MY_VAR}}"      
            - name: Print env variable
              env:
                MY_OVERWRITTEN_ENV: "step"
              run: |
               echo "Workflow env: ${{env.MY_WORKFLOW_ENV}}"
               echo "Overwritten env: ${{env.MY_OVERWRITTEN_ENV}}"
            - name: Print env variable
              run: |
               echo "Workflow env: ${{env.MY_WORKFLOW_ENV}}"
               echo "Overwritten env: ${{env.MY_OVERWRITTEN_ENV}}"
    echo-data2:
        runs-on: ubuntu-latest
        steps:
            - name: Print env variables
              run: |
               echo "Workflow env: $MY_WORKFLOW_ENV"
               echo "Overwritten env: $MY_OVERWRITTEN_ENV"
    


            
             
