name: 12 - Working with Outputs

on:
  workflow_dispatch:
     inputs:
        build-status:
            type: choice
            options:
                - success
                - failure
            default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs: 
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{steps.build.outputs.output1}}
            output2: ${{steps.build.outputs.output2}}
        steps:
            - name: Print GITHUB_OUTPUT Path
              run: echo "$GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "$GITHUB_OUTPUT"
                echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
                echo "mistake=true" > "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy
              if: ${{needs.build.outputs.build-status == 'success'}}
              run: echo 'Deploying'
            - name: Print outputs
              run: echo "${{needs.build.outputs.output1}}"

